# Introduction

Slido is a subscription software with customers purchasing year-long licences but 
customers can also use free Basic plans or purchase individual packages with rather 
low entry costs. However, mainly because of data sensitivity, large customers are keen 
to consolidate all accounts under one big deal. 


To hit the target for this quarter, our sales team needs to close at least 5 company-wide 
deals.

Below you can find some data exploration with a final recommendation which companies to target.

In [74]:
import pandas as pd
import numpy as np

# 1. Load and inspect the data

In [75]:
email_domain_data = pd.read_csv('Slido_email_domain_assignment.csv')  
email_domain_data

,account_id,event,email_domain,full_email,number_of_users,annual_plan,total_monetary,joined_participants,active_participants,avg_participant_event,avg_active_participant_event,activation_30_perc,activation_90_perc
0,48,7,lee.com,MarkVelasquezRoss@lee.com,16,Professional,5400,143,88,98.51,73.42,11,33
1,46,8,francis-ellis.com,VeronicaTerrellRowe@francis-ellis.com,19,Professional,6300,80,68,98.44,69.28,20,44
2,69,16,hale.com,TaraRosarioBrooks@hale.com,20,Professional,6600,93,51,92.11,65.55,7,28
3,39,17,mcclure.com,JenniferMillsLewis@mcclure.com,5,Enterprise,4200,136,128,92.46,65.56,6,27
4,38,27,robinson.biz,LoriJonesShepard@robinson.biz,5,Enterprise,4200,161,93,108.35,80.25,10,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,74,1988,martin.net,AngelaIrwinWilliams@martin.net,13,Professional,4500,122,80,106.43,80.14,3,25
610,74,1993,martin.net,AngelaIrwinWilliams@martin.net,13,Professional,4500,64,49,106.43,80.14,3,25
611,62,1995,jones-bradley.com,KathyGomezAllen@jones-bradley.com,2,Enterprise,2760,30,20,99.93,71.41,13,39
612,59,1997,martin.net,GeraldHudsonJr.Rivera@martin.net,3,Professional,1500,176,162,106.43,80.14,3,25
613,87,1999,turner.biz,GregoryJohnsonSmith@turner.biz,5,Professional,2100,156,106,101.20,73.92,12,30

# 2. Basic data exploration

In [76]:
email_domain_data['annual_plan'].unique()

array(['Professional', 'Enterprise', 'Engage'], dtype=object)

In [77]:
print(min(email_domain_data['joined_participants']))
print(min(email_domain_data['active_participants']))
print(min(email_domain_data['avg_participant_event']))
print(min(email_domain_data['avg_active_participant_event']))

# I'm not noticing any red flags here to exclude domains from recommendation for the company-wide deals.

5
3
70.1
54.43

In [78]:
email_domain_data_engage = email_domain_data.loc[(email_domain_data["annual_plan"] == "Engage")]
email_domain_data_engage


email_domain_data_enterprise = email_domain_data.loc[(email_domain_data["annual_plan"] == "Enterprise")]
email_domain_data_enterprise

email_domain_data_prof = email_domain_data.loc[(email_domain_data["annual_plan"] == "Professional")]
email_domain_data_prof

,account_id,event,email_domain,full_email,number_of_users,annual_plan,total_monetary,joined_participants,active_participants,avg_participant_event,avg_active_participant_event,activation_30_perc,activation_90_perc
0,48,7,lee.com,MarkVelasquezRoss@lee.com,16,Professional,5400,143,88,98.51,73.42,11,33
1,46,8,francis-ellis.com,VeronicaTerrellRowe@francis-ellis.com,19,Professional,6300,80,68,98.44,69.28,20,44
2,69,16,hale.com,TaraRosarioBrooks@hale.com,20,Professional,6600,93,51,92.11,65.55,7,28
7,52,30,martin.net,ThomasCrossMorris@martin.net,17,Professional,5700,20,16,106.43,80.14,3,25
10,87,43,turner.biz,GregoryJohnsonSmith@turner.biz,5,Professional,2100,27,17,101.20,73.92,12,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,74,1985,martin.net,AngelaIrwinWilliams@martin.net,13,Professional,4500,144,107,106.43,80.14,3,25
609,74,1988,martin.net,AngelaIrwinWilliams@martin.net,13,Professional,4500,122,80,106.43,80.14,3,25
610,74,1993,martin.net,AngelaIrwinWilliams@martin.net,13,Professional,4500,64,49,106.43,80.14,3,25
612,59,1997,martin.net,GeraldHudsonJr.Rivera@martin.net,3,Professional,1500,176,162,106.43,80.14,3,25
613,87,1999,turner.biz,GregoryJohnsonSmith@turner.biz,5,Professional,2100,156,106,101.20,73.92,12,30

In [79]:
print(email_domain_data['email_domain'].value_counts())
print('Mean total_monetary: ' + str(np.mean(email_domain_data['total_monetary'])))

martin.net           70
mcclure.com          70
robinson.biz         62
turner.biz           60
lee.com              39
guerrero.com         39
keller-potter.net    38
sutton.com           32
smith.com            30
jones-bradley.com    28
garcia.biz           25
roy.net              22
atkinson.org         21
hale.com             17
wilson.org           16
frank-mahoney.biz    16
francis-ellis.com    16
edwards.com          11
soto.biz              2
Name: email_domain, dtype: int64
Mean total_monetary: 4194.234527687297

In [80]:
print(email_domain_data_engage['email_domain'].value_counts())

print(np.mean(email_domain_data_engage['number_of_users']))
print(max(email_domain_data_engage['number_of_users']))

print('Mean total_monetary: ' + str(np.mean(email_domain_data_engage['total_monetary'])))

mcclure.com          34
robinson.biz         31
roy.net              22
guerrero.com         21
smith.com            19
keller-potter.net    17
wilson.org           16
sutton.com           12
francis-ellis.com     7
lee.com               5
Name: email_domain, dtype: int64
11.125
19
Mean total_monetary: 1455.0

In [81]:
print(email_domain_data_enterprise['email_domain'].value_counts())

print(np.mean(email_domain_data_enterprise['number_of_users']))
print(max(email_domain_data_enterprise['number_of_users']))


print('Mean total_monetary: ' + str(np.mean(email_domain_data_enterprise['total_monetary'])))

mcclure.com          36
robinson.biz         30
jones-bradley.com    28
keller-potter.net    21
atkinson.org         21
garcia.biz           19
sutton.com           18
guerrero.com         18
lee.com              16
turner.biz           12
martin.net            8
smith.com             6
Name: email_domain, dtype: int64
9.32618025751073
20
Mean total_monetary: 6276.56652360515

In [82]:
print(email_domain_data_prof['email_domain'].value_counts())

print(np.mean(email_domain_data_prof['number_of_users']))
print(max(email_domain_data_prof['number_of_users']))


print('Mean total_monetary: ' + str(np.mean(email_domain_data_prof['total_monetary'])))

martin.net           62
turner.biz           48
lee.com              18
hale.com             17
frank-mahoney.biz    16
edwards.com          11
francis-ellis.com     9
garcia.biz            6
smith.com             5
sutton.com            2
soto.biz              2
robinson.biz          1
Name: email_domain, dtype: int64
12.299492385786802
20
Mean total_monetary: 4289.84771573604

In [83]:
print(email_domain_data_prof['email_domain'].value_counts())

print(np.mean(email_domain_data_prof['number_of_users']))
print(max(email_domain_data_prof['number_of_users']))


print('Mean total_monetary: ' + str(np.mean(email_domain_data_enterprise['total_monetary'])))

martin.net           62
turner.biz           48
lee.com              18
hale.com             17
frank-mahoney.biz    16
edwards.com          11
francis-ellis.com     9
garcia.biz            6
smith.com             5
sutton.com            2
soto.biz              2
robinson.biz          1
Name: email_domain, dtype: int64
12.299492385786802
20
Mean total_monetary: 6276.56652360515

# Target options

Since large customers are keen to consolidate all accounts under one big deal, I recommend to target the largest companies first. 

Large companies can be found in multiple ways. 
Check the number of accounts on the same domain:

In [84]:
print(email_domain_data['email_domain'].value_counts()[0:10])

martin.net           70
mcclure.com          70
robinson.biz         62
turner.biz           60
lee.com              39
guerrero.com         39
keller-potter.net    38
sutton.com           32
smith.com            30
jones-bradley.com    28
Name: email_domain, dtype: int64

Or by checking the number of users under the accounts:

In [85]:
#sum all users together for each domain
email_domain_data_sum = email_domain_data.groupby('email_domain').sum()
email_domain_data_sum['number_of_users'].sort_values(ascending=False)[0:10]

email_domain
mcclure.com     808
martin.net      800
turner.biz      599
sutton.com      548
robinson.biz    477
lee.com         470
guerrero.com    396
roy.net         378
smith.com       352
hale.com        340
Name: number_of_users, dtype: int64

Another way to look at the data would be to see the number of events and how many people attended the events.

In [88]:
print(email_domain_data_sum['avg_participant_event'].sort_values(ascending=False)[0:10])
print('')
print(email_domain_data_sum['avg_active_participant_event'].sort_values(ascending=False)[0:10])

email_domain
martin.net           7450.10
robinson.biz         6717.70
mcclure.com          6472.20
turner.biz           6072.00
guerrero.com         4162.86
keller-potter.net    4115.78
lee.com              3841.89
sutton.com           3244.48
smith.com            3138.30
jones-bradley.com    2798.04
Name: avg_participant_event, dtype: float64

email_domain
martin.net           5609.80
robinson.biz         4975.50
mcclure.com          4589.20
turner.biz           4435.20
guerrero.com         3108.30
keller-potter.net    3016.06
lee.com              2863.38
smith.com            2412.30
sutton.com           2318.08
jones-bradley.com    1999.48
Name: avg_active_participant_event, dtype: float64

# Final recommendation

 For me it seems logical to target the domains with a high number of users first. 
 Since the most domains are in multiple target options the other options wouldn't be much different from this order. 
 
 So this would be my final recommendation in the following order.

| #   | Email domain |
| ----------- | :----------- |
| 1   | mcclure.com |
| 2   | martin.net |
| 3   | turner.biz |
| 4   | sutton.com |
| 5   | robinson.biz |
| 6   | lee.com |
| 7   | guerrero.com |
| 8   | roy.net  |
| 9   | smith.com |
| 10   | hale.com  |



If there are any questions or comments please let me know!
Also combinations of some target options can be an solution to come up with the best domain to target for the company-wide deal.

# Final flags and notes

Please note: 
Due to the limited time available not much research has been done in the data besides the assignment.

â€¢ Some events happened before the subscription is started. No subscription data is available. This could be really interesting to have in the dataset.  

â€¢ Why are date values not stored as DateTimes? This could be really interesting to add.